Document: shibauth
Title: Debian shibauth Manual
Author: <insert document author here>
Abstract: This manual describes what shibauth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shibauth/shibauth.sgml.gz

Format: postscript
Files: /usr/share/doc/shibauth/shibauth.ps.gz

Format: text
Files: /usr/share/doc/shibauth/shibauth.text.gz

Format: HTML
Index: /usr/share/doc/shibauth/html/index.html
Files: /usr/share/doc/shibauth/html/*.html
